import { getEnvSafely } from './config';

let MONGODB_URI, GITHUB_ID, GITHUB_SECRET, GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, NODE_ENV, AZURE_SAS_TOKEN, AZURE_STORAGE_ACCOUNT_NAME, AZURE_STORAGE_CONTAINER_NAME, NEXT_PUBLIC_API_KEY, API_URL, NEXTAUTH_URL, NEXTAUTH_SECRET;

try {
  MONGODB_URI = getEnvSafely('MONGODB_URI');
  GITHUB_ID = getEnvSafely('GITHUB_ID');
  GITHUB_SECRET = getEnvSafely('GITHUB_SECRET');
  GOOGLE_CLIENT_ID = getEnvSafely('GOOGLE_CLIENT_ID');
  GOOGLE_CLIENT_SECRET = getEnvSafely('GOOGLE_CLIENT_SECRET');
  NODE_ENV = getEnvSafely('NODE_ENV');
  AZURE_SAS_TOKEN = getEnvSafely('AZURE_SAS_TOKEN');
  AZURE_STORAGE_ACCOUNT_NAME = getEnvSafely('AZURE_STORAGE_ACCOUNT_NAME');
  AZURE_STORAGE_CONTAINER_NAME = getEnvSafely('AZURE_STORAGE_CONTAINER_NAME');
  NEXT_PUBLIC_API_KEY = getEnvSafely('NEXT_PUBLIC_API_KEY');
  API_URL = getEnvSafely('API_URL');
  NEXTAUTH_URL = getEnvSafely('NEXTAUTH_URL');
  NEXTAUTH_SECRET = getEnvSafely('NEXTAUTH_SECRET');
} catch (error) {
  console.error("Error loading environment variables:", error);
  throw error;
}

const env = {
  MONGODB_URI,
  GITHUB_ID,
  GITHUB_SECRET,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  NODE_ENV,
  AZURE_SAS_TOKEN,
  AZURE_STORAGE_ACCOUNT_NAME,
  AZURE_STORAGE_CONTAINER_NAME,
  NEXT_PUBLIC_API_KEY,
  API_URL,
  NEXTAUTH_URL,
  NEXTAUTH_SECRET,
};

export default env;